/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
    _type: 'sanity.imagePaletteSwatch';
    background?: string;
    foreground?: string;
    population?: number;
    title?: string;
};

export type SanityImagePalette = {
    _type: 'sanity.imagePalette';
    darkMuted?: SanityImagePaletteSwatch;
    lightVibrant?: SanityImagePaletteSwatch;
    darkVibrant?: SanityImagePaletteSwatch;
    vibrant?: SanityImagePaletteSwatch;
    dominant?: SanityImagePaletteSwatch;
    lightMuted?: SanityImagePaletteSwatch;
    muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
    _type: 'sanity.imageDimensions';
    height?: number;
    width?: number;
    aspectRatio?: number;
};

export type Geopoint = {
    _type: 'geopoint';
    lat?: number;
    lng?: number;
    alt?: number;
};

export type Qbank = {
    _id: string;
    _type: 'qbank';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    index?: string;
    questionType?: 'ecg' | 'qbank' | 'echo' | 'angiogram';
    title?: string;
    text?: Array<{
        children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: 'span';
            _key: string;
        }>;
        style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
        listItem?: 'bullet' | 'number';
        markDefs?: Array<{
            href?: string;
            _type: 'link';
            _key: string;
        }>;
        level?: number;
        _type: 'block';
        _key: string;
    }>;
    secondaryText?: string;
    legacyId?: number;
    correctAnswersDeprecated?: Array<{
        children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: 'span';
            _key: string;
        }>;
        style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
        listItem?: 'bullet' | 'number';
        markDefs?: Array<{
            href?: string;
            _type: 'link';
            _key: string;
        }>;
        level?: number;
        _type: 'block';
        _key: string;
    }>;
    images?: Array<{
        asset?: {
            _ref: string;
            _type: 'reference';
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
        };
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'image';
        _key: string;
    }>;
    markedImages?: Array<{
        asset?: {
            _ref: string;
            _type: 'reference';
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
        };
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'image';
        _key: string;
    }>;
    videos?: Array<{
        asset?: {
            _ref: string;
            _type: 'reference';
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
        };
        _type: 'file';
        _key: string;
    }>;
    numericIndex?: number;
    q1Text?: string;
    q1A?: string;
    q1B?: string;
    q1C?: string;
    q1D?: string;
    q1E?: string;
    q1CorrectAnswer?: 'q1A' | 'q1B' | 'q1C' | 'q1D' | 'q1E';
    q2Text?: string;
    q2A?: string;
    q2B?: string;
    q2C?: string;
    q2D?: string;
    q2E?: string;
    q2CorrectAnswer?: 'q2A' | 'q2B' | 'q2C' | 'q2D' | 'q2E';
    q3Text?: string;
    q3A?: string;
    q3B?: string;
    q3C?: string;
    q3D?: string;
    q3E?: string;
    q3CorrectAnswer?: 'q3A' | 'q3B' | 'q3C' | 'q3D' | 'q3E';
    q4Text?: string;
    q4A?: string;
    q4B?: string;
    q4C?: string;
    q4D?: string;
    q4E?: string;
    q4CorrectAnswer?: 'q4A' | 'q4B' | 'q4C' | 'q4D' | 'q4E';
    q5Text?: string;
    q5A?: string;
    q5B?: string;
    q5C?: string;
    q5D?: string;
    q5E?: string;
    q5CorrectAnswer?: 'q5A' | 'q5B' | 'q5C' | 'q5D' | 'q5E';
};

export type Angiogram = {
    _id: string;
    _type: 'angiogram';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    index?: string;
    questionType?: 'ecg' | 'qbank' | 'echo' | 'angiogram';
    title?: string;
    text?: Array<{
        children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: 'span';
            _key: string;
        }>;
        style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
        listItem?: 'bullet' | 'number';
        markDefs?: Array<{
            href?: string;
            _type: 'link';
            _key: string;
        }>;
        level?: number;
        _type: 'block';
        _key: string;
    }>;
    secondaryText?: string;
    legacyId?: number;
    correctAnswersDeprecated?: Array<{
        children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: 'span';
            _key: string;
        }>;
        style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
        listItem?: 'bullet' | 'number';
        markDefs?: Array<{
            href?: string;
            _type: 'link';
            _key: string;
        }>;
        level?: number;
        _type: 'block';
        _key: string;
    }>;
    images?: Array<{
        asset?: {
            _ref: string;
            _type: 'reference';
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
        };
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'image';
        _key: string;
    }>;
    markedImages?: Array<{
        asset?: {
            _ref: string;
            _type: 'reference';
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
        };
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'image';
        _key: string;
    }>;
    videos?: Array<{
        asset?: {
            _ref: string;
            _type: 'reference';
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
        };
        _type: 'file';
        _key: string;
    }>;
    numericIndex?: number;
    normal_angiogram_01?: number;
    left_main_severe_12?: number;
    left_anterior_severe_13?: number;
    left_circumflex_severe_14?: number;
    right_severe_15?: number;
    bypass_severe_16?: number;
    left_main_moderate_07?: number;
    left_anterior_moderate_08?: number;
    left_circumflex_moderate_09?: number;
    right_moderate_10?: number;
    bypass_moderate_11?: number;
    left_main_insignificant_02?: number;
    left_anterior_insignificant_03?: number;
    left_circumflex_insignificant_04?: number;
    right_insignificant_05?: number;
    bypass_insignificant_06?: number;
    left_main_total_occlusion_17?: number;
    left_anterior_total_occlusion_18?: number;
    left_circumflex_total_occlusion_19?: number;
    right_total_occlusion_20?: number;
    bypass_total_occlusion_21?: number;
    left_anterior_filled_collaterals_22?: number;
    left_circumflex_filled_collaterals_23?: number;
    right_filled_collaterals_24?: number;
    bypass_filled_collaterals_25?: number;
    left_anterior_coronary_spasm_26?: number;
    left_circumflex_coronary_spasm_27?: number;
    right_coronary_spasm_28?: number;
    bypass_coronary_spasm_29?: number;
    left_anterior_myocardial_bridge_34?: number;
    left_circumflex_myocardial_bridge_35?: number;
    right_coronary_myocardial_bridge_36?: number;
    left_main_anomalous_coronary_37?: number;
    left_anterior_anomalous_coronary_38?: number;
    left_circumflex_anomalous_coronary_39?: number;
    right_anomalous_coronary_40?: number;
    left_main_coronary_fistula_41?: number;
    left_anterior_coronary_fistula_42?: number;
    left_circumflex_coronary_fistula_43?: number;
    right_coronary_fistula_44?: number;
    left_anterior_coronary_thrombus_30?: number;
    left_circumflex_coronary_thrombus_31?: number;
    right_coronary_thrombus_32?: number;
    bypass_coronary_thrombus_33?: number;
    left_anterior_bypass_graft_50?: number;
    left_circumflex_bypass_graft_51?: number;
    right_bypass_graft_52?: number;
    left_main_dissection_53?: number;
    left_anterior_dissection_54?: number;
    left_circumflex_dissection_55?: number;
    right_dissection_56?: number;
    left_main_severe_ectasia_45?: number;
    left_anterior_severe_ectasia_46?: number;
    left_circumflex_severe_ectasia_47?: number;
    right_severe_ectasia_48?: number;
    bypass_severe_ectasia_49?: number;
    left_main_stent_occluded_63?: number;
    left_anterior_stent_occluded_64?: number;
    left_circumflex_stent_occluded_65?: number;
    right_stent_occluded_66?: number;
    bypass_stent_occluded_67?: number;
    left_main_stent_patent_58?: number;
    left_anterior_stent_patent_59?: number;
    left_circumflex_stent_patent_60?: number;
    right_stent_patent_61?: number;
    bypass_stent_patent_62?: number;
};

export type Echo = {
    _id: string;
    _type: 'echo';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    index?: string;
    questionType?: 'ecg' | 'qbank' | 'echo' | 'angiogram';
    title?: string;
    text?: Array<{
        children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: 'span';
            _key: string;
        }>;
        style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
        listItem?: 'bullet' | 'number';
        markDefs?: Array<{
            href?: string;
            _type: 'link';
            _key: string;
        }>;
        level?: number;
        _type: 'block';
        _key: string;
    }>;
    secondaryText?: string;
    legacyId?: number;
    correctAnswersDeprecated?: Array<{
        children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: 'span';
            _key: string;
        }>;
        style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
        listItem?: 'bullet' | 'number';
        markDefs?: Array<{
            href?: string;
            _type: 'link';
            _key: string;
        }>;
        level?: number;
        _type: 'block';
        _key: string;
    }>;
    images?: Array<{
        asset?: {
            _ref: string;
            _type: 'reference';
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
        };
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'image';
        _key: string;
    }>;
    markedImages?: Array<{
        asset?: {
            _ref: string;
            _type: 'reference';
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
        };
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'image';
        _key: string;
    }>;
    videos?: Array<{
        asset?: {
            _ref: string;
            _type: 'reference';
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
        };
        _type: 'file';
        _key: string;
    }>;
    numericIndex?: number;
    lv_vs_rupture_04?: number;
    lv_fw_rupture_05?: number;
    lv_ruptured_papillary_06?: number;
    lv_size_small_03?: number;
    lv_size_normal_01?: number;
    lv_size_enlarged_02?: number;
    lv_wall_normal_07?: number;
    lv_concentric_increase_08?: number;
    lv_asymmetric_09?: number;
    lv_mass_or_thrombus_10?: number;
    lv_metastatic_tumor_11?: number;
    lv_ejection_normal_12?: number;
    lv_ejection_mild_13?: number;
    lv_ejection_severe_14?: number;
    lv_diastolic_normal_15?: number;
    lv_diastolic_grade_1_16?: number;
    lv_diastolic_grade_2_17?: number;
    lv_diastolic_grade_3_18?: number;
    lv_abnormal_wall_19?: number;
    lv_global_hypokinesis_20?: number;
    apical_hypokinesis_25?: number;
    septal_hypokinesis_22?: number;
    lateral_hypokinesis_23?: number;
    inferior_hypokinesis_24?: number;
    anterior_hypokinesis_21?: number;
    apical_akinesis_30?: number;
    septal_akinesis_27?: number;
    lateral_akinesis_28?: number;
    inferior_akinesis_29?: number;
    anterior_akinesis_26?: number;
    apical_thinning_35?: number;
    septal_thinning_32?: number;
    lateral_thinning_33?: number;
    inferior_thinning_34?: number;
    anterior_thinning_31?: number;
    apical_aneurysm_40?: number;
    septal_aneurysm_37?: number;
    lateral_aneurysm_38?: number;
    inferior_aneurysm_39?: number;
    anterior_aneurysm_36?: number;
    apical_pseudoaneurysm_45?: number;
    septal_pseudoaneurysm_42?: number;
    lateral_pseudoaneurysm_43?: number;
    inferior_pseudoaneurysm_44?: number;
    anterior_pseudoaneurysm_41?: number;
    apical_ischemia_50?: number;
    septal_ischemia_47?: number;
    lateral_ischemia_48?: number;
    inferior_ischemia_49?: number;
    anterior_ischemia_46?: number;
    apical_viability_55?: number;
    septal_viability_52?: number;
    lateral_viability_53?: number;
    inferior_viability_54?: number;
    anterior_viability_51?: number;
    primum_asd_57?: number;
    secundum_asd_58?: number;
    sinus_asd_59?: number;
    patent_foramen_ovale_56?: number;
    muscular_vsd_60?: number;
    membranous_vsd_61?: number;
    supacristal_vsd_62?: number;
    patent_ductus_arteriosus_63?: number;
    subaortic_stenosus_64?: number;
    coronary_fistula_65?: number;
    tetralogy_of_fallot_66?: number;
    ebsteins_anomaly_67?: number;
    anomalous_coronary_artery_148?: number;
    complete_transposition_68?: number;
    corrected_transposition_69?: number;
    enlarged_left_atrium_70?: number;
    enlarged_right_atrium_71?: number;
    atrial_myxoma_72?: number;
    atrial_thrombus_73?: number;
    metastatic_tumor_74?: number;
    atrial_hypertrophy_75?: number;
    dilated_cardiomyopathy_80?: number;
    hypertrophic_cardiomyopathy_76?: number;
    apical_cardiomyopathy_77?: number;
    restrictive_cardiomyopathy_78?: number;
    takotsubo_cardiomyopathy_82?: number;
    arvd_cardiomyopathy_79?: number;
    noncompaction_cardiomyopathy_81?: number;
    amyloid_83?: number;
    hypereosinophilia_84?: number;
    vegetation_aortic_88?: number;
    calcified_aortic_85?: number;
    bicuspid_aortic_87?: number;
    flail_aortic_89?: number;
    fibroelastoma_aortic_90?: number;
    abscess_aortic_91?: number;
    rheumatic_aortic_86?: number;
    vegetation_mitral_95?: number;
    calcified_mitral_92?: number;
    cleft_mitral_94?: number;
    prolapse_mitral_96?: number;
    flail_mitral_97?: number;
    fibroelastoma_mitral_98?: number;
    sam_mitral_99?: number;
    rheumatic_mitral_93?: number;
    vegetation_tricuspid_102?: number;
    fails_tricuspid_100?: number;
    carcinoid_tricuspid_101?: number;
    prolapse_tricuspid_103?: number;
    flail_tricuspid_104?: number;
    congenitally_abnormal_105?: number;
    carcinoid_106?: number;
    normal_prosthetic_107?: number;
    prosthetic_endocarditis_113?: number;
    pathologic_prosthetic_108?: number;
    perivalvular_prosthetic_109?: number;
    elevated_prosthetic_110?: number;
    obstruction_prosthetic_111?: number;
    dehiscense_prosthetic_112?: number;
    mild_mitral_stenosis_108?: number;
    mild_aortic_stenosis_107?: number;
    mild_pulmonic_stenosis_110?: number;
    mild_tricuspid_stenosis_109?: number;
    mild_mitral_regurgitation_112?: number;
    mild_aortic_regurgitation_111?: number;
    mild_pulmonic_regurgitation_114?: number;
    mild_tricuspid_regurgitation_113?: number;
    severe_mitral_stenosis_116?: number;
    severe_aortic_stenosis_115?: number;
    severe_pulmonic_stenosis_118?: number;
    severe_tricuspid_stenosis_117?: number;
    severe_mitral_regurgitation_120?: number;
    severe_aortic_regurgitation_119?: number;
    severe_pulmonic_regurgitation_122?: number;
    severe_tricuspid_regurgitation_121?: number;
    acute_pulmonary_embolism_123?: number;
    acute_pulmonary_hypertension_124?: number;
    type_a_dissection_126?: number;
    type_b_dissection_127?: number;
    marfan_syndrome_125?: number;
    intramural_hematoma_128?: number;
    aortic_ulcer_129?: number;
    aortic_enlargement_130?: number;
    aortic_rupture_131?: number;
    valsalva_aneurysm_132?: number;
    valsalva_rupture_133?: number;
    coarctation_134?: number;
    pericardial_effusion_135?: number;
    tamponade_136?: number;
    pericardial_mass_137?: number;
    pericardial_constriction_138?: number;
    pericardial_cyst_139?: number;
    pleural_effusion_140?: number;
    enlarged_rv_141?: number;
    rv_intact_142?: number;
    global_hypokinesis_143?: number;
    rv_volume_overload_144?: number;
    rv_pressure_overload_145?: number;
    catheter_pacemaker_wire_146?: number;
    rv_mass_thrombus_147?: number;
};

export type Ecg = {
    _id: string;
    _type: 'ecg';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    index?: string;
    questionType?: 'ecg' | 'qbank' | 'echo' | 'angiogram';
    title?: string;
    text?: Array<{
        children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: 'span';
            _key: string;
        }>;
        style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
        listItem?: 'bullet' | 'number';
        markDefs?: Array<{
            href?: string;
            _type: 'link';
            _key: string;
        }>;
        level?: number;
        _type: 'block';
        _key: string;
    }>;
    secondaryText?: string;
    legacyId?: number;
    correctAnswersDeprecated?: Array<{
        children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: 'span';
            _key: string;
        }>;
        style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
        listItem?: 'bullet' | 'number';
        markDefs?: Array<{
            href?: string;
            _type: 'link';
            _key: string;
        }>;
        level?: number;
        _type: 'block';
        _key: string;
    }>;
    images?: Array<{
        asset?: {
            _ref: string;
            _type: 'reference';
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
        };
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'image';
        _key: string;
    }>;
    markedImages?: Array<{
        asset?: {
            _ref: string;
            _type: 'reference';
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
        };
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'image';
        _key: string;
    }>;
    videos?: Array<{
        asset?: {
            _ref: string;
            _type: 'reference';
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
        };
        _type: 'file';
        _key: string;
    }>;
    numericIndex?: number;
    normal_01?: number;
    borderline_normal_normal_variant_ecg_02?: number;
    incorrect_electrode_placement_03?: number;
    artifact_04?: number;
    right_atrial_enlargement_05?: number;
    left_atrial_enlargement_06?: number;
    sinus_rhythm_07?: number;
    sinus_arrhythmia_08?: number;
    sinus_bradycardia_09?: number;
    sinus_tachycardia_10?: number;
    sinus_pause_or_arrest_11?: number;
    sinoatrial_sa_exit_block_12?: number;
    atrial_premature_complexes_apc_13?: number;
    atrial_tachycardia_14?: number;
    multifocal_atrial_tachycardia_mat_15?: number;
    supraventricular_tachycardia_svt_16?: number;
    atrial_flutter_17?: number;
    atrial_fibrillation_18?: number;
    av_junctional_premature_complexes_jpc_19?: number;
    av_junctional_escape_complex_es_20?: number;
    av_junctional_rhythmtachycardia_21?: number;
    ventricular_premature_complexes_vpc_22?: number;
    ventricular_parasystole_23?: number;
    ventricular_tachycardia_3_successive_vpcs_vt_24?: number;
    accelerated_idioventricular_rhythm_aivr_25?: number;
    ventricular_escape_complexesrhythm_26?: number;
    ventricular_fibrillation_vf_27?: number;
    av_block_1_28?: number;
    av_block_2_mobitz_type_i_wenckebach_29?: number;
    av_block_2_mobitz_type_ii_30?: number;
    av_block_2_1_31?: number;
    av_block_3_complete_heart_block_32?: number;
    wolff_parkinson_white_pattern_wpw_33?: number;
    av_dissociation_34?: number;
    low_voltage_limb_leads_35?: number;
    low_voltage_precordial_leads_36?: number;
    left_axis_deviation_37?: number;
    right_axis_deviation_38?: number;
    electrical_alternans_39?: number;
    left_ventricular_hypertrophy_lvh_40?: number;
    right_ventricular_hypertrophy_rvh_41?: number;
    combined_ventricular_hypertrophy_42?: number;
    brugada_syndrome_70?: number;
    digitalis_toxicity_71?: number;
    torsades_de_pointes_72?: number;
    hyperkalemia_73?: number;
    hypokalemia_74?: number;
    hypercalcemia_75?: number;
    hypocalcemia_76?: number;
    dextrocardia_mirror_image_77?: number;
    acute_cor_pulmonale_pulmonary_embolus_78?: number;
    pericardial_effusion_79?: number;
    acute_pericarditis_80?: number;
    hypertrophic_cardiomyopathy_hcm_81?: number;
    central_nervous_system_cns_disorder_82?: number;
    hypothermia_83?: number;
    right_bundle_branch_block_complete_rbbb_43?: number;
    right_bundle_branch_block_incomplete_irbbb_44?: number;
    left_posterior_fascicular_block_lpfb_46?: number;
    left_anterior_fascicular_block_lafb_45?: number;
    left_bundle_branch_block_complete_lbbb_47?: number;
    left_bundle_branch_block_incomplete_ilbbb_48?: number;
    aberrant_conduction_including_rate_related_49?: number;
    nonspecific_iv_conduction_disturbance_50?: number;
    anterolateral_mi_acute_recent_51?: number;
    anterolateral_mi_old_indeterminate_52?: number;
    anterior_or_anteroseptal_mi_acute_recent_53?: number;
    anterior_anteroseptal_mi_old_indeterminate_54?: number;
    lateral_mi_acute_recent_55?: number;
    lateral_mi_old_indeterminate_56?: number;
    inferior_mi_acute_recent_57?: number;
    inferior_mi_old_indeterminate_58?: number;
    posterior_mi_acute_recent_59?: number;
    posterior_mi_old_indeterminate_60?: number;
    early_repolarization_normal_variant_61?: number;
    juvenile_t_waves_normal_variant_62?: number;
    st_t_changes_nonspecific_63?: number;
    st_t_changes_suggesting_myocardial_ischemia_64?: number;
    st_t_changes_suggesting_myocardial_injury_65?: number;
    st_t_changes_suggesting_electrolyte_disturbance_66?: number;
    st_t_changes_of_hypertrophy_67?: number;
    prolonged_qt_interval_68?: number;
    prominent_u_waves_69?: number;
    atrial_or_coronary_sinus_pacing_84?: number;
    ventricular_demand_pacemaker_vvi_normal_85?: number;
    dual_chamber_pacemaker_ddd_normal_86?: number;
    pacemaker_malfunction_failure_to_capture_87?: number;
    pacemaker_malfunction_failure_to_sense_88?: number;
    biventricular_pacing_89?: number;
};

export type SanityFileAsset = {
    _id: string;
    _type: 'sanity.fileAsset';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    originalFilename?: string;
    label?: string;
    title?: string;
    description?: string;
    altText?: string;
    sha1hash?: string;
    extension?: string;
    mimeType?: string;
    size?: number;
    assetId?: string;
    uploadId?: string;
    path?: string;
    url?: string;
    source?: SanityAssetSourceData;
};

export type SanityImageCrop = {
    _type: 'sanity.imageCrop';
    top?: number;
    bottom?: number;
    left?: number;
    right?: number;
};

export type SanityImageHotspot = {
    _type: 'sanity.imageHotspot';
    x?: number;
    y?: number;
    height?: number;
    width?: number;
};

export type SanityImageAsset = {
    _id: string;
    _type: 'sanity.imageAsset';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    originalFilename?: string;
    label?: string;
    title?: string;
    description?: string;
    altText?: string;
    sha1hash?: string;
    extension?: string;
    mimeType?: string;
    size?: number;
    assetId?: string;
    uploadId?: string;
    path?: string;
    url?: string;
    metadata?: SanityImageMetadata;
    source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
    _type: 'sanity.assetSourceData';
    name?: string;
    id?: string;
    url?: string;
};

export type SanityImageMetadata = {
    _type: 'sanity.imageMetadata';
    location?: Geopoint;
    dimensions?: SanityImageDimensions;
    palette?: SanityImagePalette;
    lqip?: string;
    blurHash?: string;
    hasAlpha?: boolean;
    isOpaque?: boolean;
};

export type MediaTag = {
    _id: string;
    _type: 'media.tag';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name?: Slug;
};

export type Slug = {
    _type: 'slug';
    current?: string;
    source?: string;
};

export type AllSanitySchemaTypes =
    | SanityImagePaletteSwatch
    | SanityImagePalette
    | SanityImageDimensions
    | Geopoint
    | Qbank
    | Angiogram
    | Echo
    | Ecg
    | SanityFileAsset
    | SanityImageCrop
    | SanityImageHotspot
    | SanityImageAsset
    | SanityAssetSourceData
    | SanityImageMetadata
    | MediaTag
    | Slug;
export declare const internalGroqTypeReferenceTo: unique symbol;
